# -*- coding: utf-8 -*-
"""22.04.2022 udemy lesson notes- 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pblf2DZNlTz1GgTC5xzW3N4xEWD-I4it
"""

s = 'Python'

help(s)

help(s.count)

s

pi_sayısı = 3.14
çap = 4
çevre = pi_sayısı * çap
çevre

a = 4
b = 3

a,b = b,a

print(a, b)

i = 5
i = i + 1  # i+=1 bu şekilde de yazabiliriz.
i

b = 3
b *= 4  #(b=b*4)
b

# Tekli yorum satırı
print("asuman")

"""
Çoklu yorum satırı

"""
print('asuman')

k = 34
l = 45
m = 54
k + l + m

k - l

k * l * m

k / l

i = 3.14
j = 4.3
i + j
i * j

4 // 2 #tam sayı bölmesi (integer)

4 / 2  #flaot değer.

80.45 // 40

82.74 / 45.20

13 % 4  #modulus 4 yani kalanı veriyor.

22.7 % 11.4

4 ** 2   #4 ün karesi

16 ** 0.5   # 16 nın karekökü

8 ** (1/3) #küp kök işlemi

a = -4 #sayıların işaretlerini değiştirme.
-a

#işlem sırası
#parantez içi,
#çarpma, bölme,
#toplama çıkarma
#soldan sağa

"asuman"

'asuman'

'''asuman'''

'asuman\'ın I T  kursu'

#indexleme slashlama
a = 'HerşeyGüzelOlacak'

a[1:8:2]

a[:]

a[::2] #başlangıç, bitiş yok, 2 şer atla

a[::-1] #ters döndür.

len(a)

"""string ler direkt olarak değiştirilemez.             
string = 'Merhaba'          
string[3] = 't'          
yapılamaz.       
"""

'a'*3    #burada ise string olan a yı 3 kez yazdırdık.

a*3  #burada a değişkenini 3 le çarpıp yazdırdık.

#mülakat sorusu olabilir
#stringler değişmez.buradaki konu a değişkeninin değerinin bir sonraki satırda değişmesi.
a = 'Asuman '
a = a + 'KAMBEROĞLU'
a

a = 43
a = float(a)

a

b = 3.14
int(b)

#sayıları str e çevirmek için STR fonk. kullanıyoruz.
a =  33558899
b = str(a)
b

len(b)

x = str(345)

x

len(x)

w = "3254895akieatuieanhuia" #bir string i integer a çevirmek istiyorsak içerisinde bulunan tüm karakterlerin 10 luk tabanda olması gerekiyor.
int(w)

# print fonksiyonları ve formatlama metodları
print("Asuman KAMBEROĞLU")
print(35)
print(3.14)
print('Asuman')
print("Asuman KAMBEROĞLU", "2022", "Udemy Çalışmaları")

a = 4
b = 15
print(a+b)

print("Asuman KAMBEROĞLU\n2022\nUdemy Çalışmaları")

print("Asuman KAMBEROĞLU\t2022\tudemy Çalışmaları")

print("ocak\tŞubat\tMart\tNisan")

type(4)

# sep parametresi
print(35, 43, 54, 89)

print(35, 25, 63, 89, sep = "*")

print(*"Asuman") #seperasyon yaptı.

print(*"Asuman", sep = "/")

print(*"TBMM", sep = ".")

# formatlama metodu
"{} {} {}".format(3, 5, 7)

a = 3
b = 4
print("{} + {}'ün toplamı {}'dir".format(a, b, a+b))

"{1} {0} {2}".format('20 Nisan', 'Ankara', 2022)

"{:.2f} {:.2f} {:.3f}".format(3.125499, 2.598456, 6.6984566)

